### ISSUE TITLE
Suggestion: allow messages to be sent before closing the socket

### ISSUE THREAD

**Issue by icehaunter** [mtrudel/sock#11]
I think it may be a good idea to add `:close` atom value to allowed control opcodes, so that `handle_in/2` and `handle_info/2` could choose to push some data into the socket and close it immediately afterwards.

I ran into this issue while experimenting with moving a custom binary protocol websocket handler from Cowboy to Bandit with WebSock. Current implementation does some initial handshake-style message passing, and in case of failure it sends an in-protocol detailed error before closing the connection. I find it a valuable feature, especially for a binary protocol, since it allows giving the client some actionable context about a failed handshake.

I understand that I could do a `send(self(), :do_close)` call and a `{:push, {:binary, error_message}, %{state | to_be_closed: true}}` return, and add a special-case handler in `handle_in/2` and `handle_info/2` that would return a `{:stop, :normal, state}` tuple if the `to_be_closed` flag is set to `true`, but I think that allowing ` :close` atom is a more appropriate solution for this problem. It seems to me that the concern of "push some data and close right after" is a generic one

**Comment by mtrudel** [comment]
First up: I agree this is a valuable feature and something we should do! 

In terms of mechanism, I'm a little anxious about allowing a `:close` tuple to be sent like `{:push, {:close, 1000}, state}`, mostly because the message parameter is allowed to be a list of frames to send, and so return values like `{:push, [{:text, "Goodbye"}, {:close, 1000}, {:text, "Now what?"}], state}` lead to some awkward edge cases. That's explicitly the reason that Bandit doesn't support sending close tuples except as a side effect of closing the connection.  

I'd rather see a `:stop` tuple with an optional 'list of messages to send before closing' parameter; something like `{:stop, :normal, code, msg, state}` for the happy path, and `{:stop, reason, code, msg, state}` for the sad path. 

WDYT?

**Comment by mtrudel** [comment]
Somewhat related to https://github.com/phoenixframework/websock_adapter/issues/2

**Comment by josevalim** [comment]
`{:close, code, messages, state}` works for me. `:stop` as well.

**Comment by icehaunter** [comment]
@mtrudel, thanks for a prompt reply! I'm glad you're onboard with this feature existing.

I agree that Cowboy's way of allowing a `:close` statement wherever in messages and just discarding the rest feels somewhat not-explicit. I think a `:stop`/`:close` tuple with an explicit list of messages to be sent is a good clear option.

Adding a 5-arity stop tuple to existing 3-arity and 4-arity feels reasonable, if maybe a bit hard to juggle with `{:shutdown, :restart}` value for the second tuple element. I think I mildly prefer `:stop` to `:close` because it conveys the fact that the websocket process is going to stop a little better, but I'm not sure I have much more to offer as far as my opinion goes.

**Comment by mtrudel** [comment]
I'll get this worked up in the next couple of days!

**Comment by mtrudel** [comment]
Candidate API change up for review at https://github.com/phoenixframework/websock/pull/12

**Comment by mtrudel** [comment]
Merged as part of WebSock `0.5.3`, implemented in WebSockAdapters `0.5.4` & Bandit `1.0.0-pre.13`, both just published. 

Thanks for the suggestion!
